# Generated by Django 5.2.11 on 2026-02-22 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('icone', models.ImageField(blank=True, null=True, upload_to='icones_categorias/')),
                ('tempo_estimado_resolucao', models.IntegerField(help_text='Tempo estimado para resolução em dias')),
            ],
        ),
        migrations.CreateModel(
            name='RelatoZeladoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Descrição detalhada do cidadão')),
                ('foto_problema', models.ImageField(upload_to='relatos_cidadao/')),
                ('latitude', models.FloatField(blank=True, help_text='Latitude', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude', null=True)),
                ('endereco_aproximado', models.CharField(blank=True, max_length=255)),
                ('status_atual', models.CharField(choices=[('recebido', 'Recebido'), ('em_analise', 'Em Análise'), ('equipe_despachada', 'Equipe no Local'), ('resolvido', 'Resolvido'), ('rejeitado', 'Rejeitado / Improcedente')], default='recebido', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_marica_cidadao.categoriaproblema')),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('em_analise', 'Em Análise'), ('equipe_despachada', 'Equipe no Local'), ('resolvido', 'Resolvido'), ('rejeitado', 'Rejeitado / Improcedente')], max_length=20)),
                ('observacao_prefeitura', models.TextField(blank=True, help_text="Mensagem da prefeitura para o cidadão (ex: 'Buraco tapado com sucesso')")),
                ('foto_resolucao', models.ImageField(blank=True, null=True, upload_to='resolucoes_prefeitura/')),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
                ('atualizado_por', models.ForeignKey(help_text='Servidor da prefeitura que atualizou o status', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('relato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='app_marica_cidadao.relatozeladoria')),
            ],
            options={
                'ordering': ['-data_atualizacao'],
            },
        ),
    ]
