# Generated by Django 5.2.11 on 2026-02-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marica_cidadao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatozeladoria',
            name='endereco_aproximado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
