# Generated by Django 5.2.9 on 2026-02-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marica_cidadao', '0003_alter_historicostatus_atualizado_por_perfilcidadao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicostatus',
            options={'ordering': ['-data_atualizacao'], 'verbose_name': 'Histórico de Status', 'verbose_name_plural': 'Históricos de Status'},
        ),
        migrations.AddField(
            model_name='relatozeladoria',
            name='avaliacao',
            field=models.IntegerField(blank=True, help_text='Avaliação de 1 a 5 estrelas', null=True),
        ),
        migrations.AddField(
            model_name='relatozeladoria',
            name='comentario_cidadao',
            field=models.TextField(blank=True, help_text='Comentário do cidadão sobre a resolução', null=True),
        ),
    ]
