# Generated by Django 5.2.9 on 2026-02-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marica_cidadao', '0004_alter_historicostatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatozeladoria',
            name='comprovante_titularidade',
            field=models.FileField(blank=True, help_text='Necessário se for propriedade privada', null=True, upload_to='comprovantes_relatos/'),
        ),
        migrations.AddField(
            model_name='relatozeladoria',
            name='e_propriedade_privada',
            field=models.BooleanField(default=False, help_text='O problema é em uma propriedade privada?'),
        ),
    ]
