# Generated by Django 5.2.9 on 2026-02-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marica_cidadao', '0005_relatozeladoria_comprovante_titularidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproblema',
            name='emoji',
            field=models.CharField(blank=True, help_text='Emoji para exibição no formulário', max_length=10, null=True),
        ),
    ]
