# Generated by Django 5.2.9 on 2026-02-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marica_cidadao', '0006_categoriaproblema_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatozeladoria',
            name='aceite_termo_ambiental',
            field=models.BooleanField(default=False, help_text='Ciente da compensação ambiental conforme Lei 2367/2011'),
        ),
    ]
