# Generated by Django 5.2.9 on 2026-02-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marica_cidadao', '0007_relatozeladoria_aceite_termo_ambiental'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatozeladoria',
            name='foto_galeria',
            field=models.ImageField(blank=True, help_text='Foto enviada da galeria', null=True, upload_to='relatos_cidadao/'),
        ),
        migrations.AlterField(
            model_name='relatozeladoria',
            name='foto_problema',
            field=models.ImageField(blank=True, help_text='Foto tirada na hora (Câmera)', null=True, upload_to='relatos_cidadao/'),
        ),
    ]
