# Generated by Django 5.2.9 on 2026-03-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marica_cidadao', '0008_relatozeladoria_foto_galeria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatozeladoria',
            name='foto_galeria',
        ),
        migrations.AlterField(
            model_name='relatozeladoria',
            name='foto_problema',
            field=models.ImageField(blank=True, help_text='Foto do problema (obrigatório)', null=True, upload_to='relatos_cidadao/'),
        ),
    ]
