# Generated by Django 5.2.9 on 2026-03-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marica_cidadao', '0009_remove_relatozeladoria_foto_galeria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatozeladoria',
            name='justificativa_ia',
            field=models.TextField(blank=True, help_text='Explicação técnica da IA', null=True),
        ),
        migrations.AddField(
            model_name='relatozeladoria',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='baixa', help_text='Estimada pela IA ou servidora', max_length=20),
        ),
    ]
