# Generated by Django 5.2.9 on 2026-03-11 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marica_cidadao', '0010_relatozeladoria_justificativa_ia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproblema',
            options={'verbose_name': 'Categoria de Problema', 'verbose_name_plural': 'Categorias de Problemas'},
        ),
        migrations.AlterModelOptions(
            name='perfilcidadao',
            options={'verbose_name': 'Perfil do Cidadão', 'verbose_name_plural': 'Perfis dos Cidadãos'},
        ),
        migrations.AlterModelOptions(
            name='relatozeladoria',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Relato de Zeladoria', 'verbose_name_plural': 'Relatos de Zeladoria'},
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(help_text='URL gerada pelo serviço de push do navegador', max_length=500, unique=True)),
                ('p256dh', models.CharField(help_text='Chave pública do dispositivo (ECDH)', max_length=200)),
                ('auth', models.CharField(help_text='Segredo de autenticação do dispositivo', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webpush_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscrição WebPush',
                'verbose_name_plural': 'Inscrições WebPush',
            },
        ),
    ]
