# Generated by Django 5.2.9 on 2026-03-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marica_cidadao', '0011_alter_categoriaproblema_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatozeladoria',
            name='bairro',
            field=models.CharField(blank=True, help_text='Bairro onde o problema ocorreu', max_length=150, null=True),
        ),
    ]
